name: conditional-example
on: [push]
jobs:
  hello-world:
    if: github.repository == 'rigers007/Github-Examples'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run:  echo "Hello World!"
  goodbye-moon:
    runs-on: ubuntu-latest
    steps:
      - name: "Goodbye Moon"
        run:  echo "Goodbye Moon!"
  action-owner:
    runs-on: ubuntu-latest
    steps:
    -name: Get the actor of the action
    run: echo "The author of the action is ${{github.actor}}"
